config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'locations/index'
  get 'locations/new', to: 'locations#new'
  get 'locations/get_locations', to: 'locations#get_locations'
  get 'locations/get_beer', to: 'locations#get_all_beer'
  get 'locations/get_wine', to: 'locations#get_all_wine'
  get 'locations/get_liquor', to: 'locations#get_all_liquor'
  get 'locations/get_all_locations', to: 'locations#get_all_locations'
  root to: 'locations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :locations do
    collection do
      post :import
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  require 'set'
  has_many :taggings
  has_many :tags, through: :taggings

  geocoded_by :street_address
  reverse_geocoded_by :latitude, :longitude

  def get_locations(pos)
    # Location.near([pos.lat, pos.lng], 10)
  end

  def get_all_locations
    Location.all
  end

  scope :all_with_geo, -> {Location.all.where.not(latitude: nil)}

  scope :get_all_beer, -> {Location.where(beer: true).where.not(latitude: nil)}

  scope :get_all_wine, -> {Location.where(wine: true).where.not(latitude: nil)}

  scope :get_all_liquor, -> {Location.where(liquor: true).where.not(latitude: nil)}

  def street_address
    "#{address['street_address']} #{address['city']} #{address['zip']}"
  end

  scope :within_5, -> (lat, lng) {near([lat, lng], 5)}

  def self.import(file)
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|

      row = Hash[[header, spreadsheet.row(i)].transpose]
      location = Location.find_by(license: row["license"]) || new

      if row["dba"].nil?
        next
      end
      if row['license'].nil?
        next
      end

      row.delete(nil)

      if row['license'].include? "BC"
        location.beer = true
        location.license_type = "Banquet Catering"
      end
      if row['license'].include? 'BE'
        location.beer = true
        location.license_type = "On Premise Beer"
      end

      if row['license'].include? 'CL'
        location.liquor = true
        location.license_type = "Private Club"
      end

      if row['license'].include? 'PS'
        location.beer = true
        location.license_type = 'Public Service Permit'
      end

      if row['license'].include? 'RB'
        location.beer = true
        location.license_type = 'Restaurant - Beer Only'
      end

      if row['license'].include? 'RL'
        location.wine = true
        location.license_type = 'Restaurant - Limited Service'
      end

      if row['license'].include? 'RE'
        location.liquor = true
        location.license_type = 'Restaurant - Full Service'
      end

      if row['license'].include? 'TV'
        location.beer = true
        location.license_type = 'Tavern'
      end

      location.license = row["license"]
      location.name = row["dba"]
      location.address = {
        street_address: row['address'],
        city: row['city'],
        state: row['state'],
        zip: row['zip']
      }
      location.phone = row['phone']
      location.save!
    end

  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :locations, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/base_api_controller.rb
class BaseApiController < ApplicationController
  before_filter :parse_request, :authenticate_user_from_token!

  private
  def authenticate_user_from_token!
    if !@json['api_token']
      render nothing: true, status: :unauthorized
    else
      @user = nil
      User.find_each do |u|
        if Devise.secure_compare(u.api_token, @json['api_token'])
          @user = u
        end
      end
    end
  end

  def parse_request
    @json = JSON.parse(request.body.read)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_admin!, only: [:new]
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper


  def index

  end

  def get_locations

    # locations = Location.near([params[:lat], params[:lng]], 5)
    locations = Location.all
    render json: locations.to_json
  end

  def get_all_beer
    beer = Location.get_all_beer
    render json: beer.to_json
  end

  def get_all_wine
    wine = Location.get_all_wine
    render json: wine.to_json
  end

  def get_all_liquor
    liquor = Location.get_all_liquor
    render json: liquor.to_json
  end

  def get_all_locations
    locations = Location.all_with_geo
    render json: locations.to_json
  end

  def new
    location_scope = Location.all

    # location_scope = location_scope.where("name ilike '%#{params[:filter]}%'")

    location_scope = location_scope.where(longitude: nil) if params[:missing_longitude] == "1"
    @locations = smart_listing_create(:locations, location_scope, partial: "locations/listing")
  end

  def import
    Location.import(params[:file])

    redirect_to locations_new_path, notice: 'Locations imported'
  end

  private

  def location_params
    params.require(:location).permit(:name, :address, :city, :state, :zip, :phone, :license, :latitude, :longitude, :pos )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_api_helper.rb
module BaseApiHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Brand", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path%> <span class="sr-only">(current)</span></a></li>

        <% if admin_signed_in? %>
            <li>
              <%= link_to "Locations", locations_new_path %>
            </li>
            <li>
              <%= link_to('Logout', destroy_admin_session_path, method: :delete) %>
            </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLiquorChecker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
  <%= render partial: "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/index.js.erb
<%= smart_listing_update(:locations) %>

app/views/locations/_listing.html.erb
<% unless smart_listing.empty? %>
    <%= smart_listing_controls_for(:locations, {class: "form-inline text-right"}) do %>
      <div class="checkbox">
        <label class="checkbox inline">
          <%= hidden_field_tag :missing_longitude, "0"%>
          <%= check_box_tag :missing_longitude %>
          <%= "Missing Geolocation"%>
        </label>
      </div>
        <form>
          <div class="form-group filter input-append">
            <%= text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off %>
            <button class="btn btn-primary disabled" type="submit">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </div>
        </form>

    <% end %>
  <table class="table table-striped">
    <thead>
      <th>Name</th>

      <th>License</th>
    </thead>
    <tbody>
      <% smart_listing.collection.each do |location| %>
        <tr>
          <td>
            <%= location.name.titleize %>
          </td>

        <td>
          <%= location.license_type %>
        </td>

        </tr>
      <% end %>
    </tbody>
  </table>
    <%= smart_listing.paginate %>
    <%= smart_listing.pagination_per_page_links %>
<% else %>
    <p class="warning">No Records</p>
<% end %>

app/views/locations/index.html.erb
<h1>Add javascript showing locations. </h1>
<h4>Find ways to filter, get icons to represent</h4>

<div class="col-md-6" id="map"></div>
<div class="col-md-6">
  <div class="row">
    <div class="col-sm-2">
      <h3 class="filter-h3">Beer</h3>
    </div>
    <div class="col-sm-8">
      <button type="button" class="btn btn-lg btn-toggle active" data-toggle="button" aria-pressed="true" autocomplete="off">
        <div class="handle"></div>
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <h3 class="filter-h3">Wine</h3>
    </div>
    <div class="col-sm-8">
      <button type="button" class="btn btn-lg btn-toggle active" data-toggle="button" aria-pressed="true" autocomplete="off">
        <div class="handle"></div>
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <h3 class="filter-h3">Liquor</h3>
    </div>
    <div class="col-sm-8">
      <button type="button" class="btn btn-lg btn-toggle active" data-toggle="button" aria-pressed="true" autocomplete="off">
        <div class="handle"></div>
      </button>
    </div>
  </div>
</div>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCczr19bUvevRjoBOSzoW5THnrcAL8m6dA&callback=initMap"
        type="text/javascript"></script>

app/views/locations/new.html.erb
<h1>Locations</h1>

<%= smart_listing_render(:locations) %>

<div class="well">
  <h3>Import new locations</h3>
  <h4>Some notes before importing.</h4>
  <ul>
    <li>
      The download from DABC does not include headers. You must put that in.
    </li>
    <li>
      Export to CSV format.
    </li>
    <li>
      Then upload.
    </li>
  </ul>
  </ul>
</div>
<%= form_tag import_locations_path, multipart: true do %>
    <div class="form-group">
      <%= file_field_tag :file %>
    </div>
    <div>
      <%= submit_tag "Import", class: "btn btn-default" %>
    </div>

<% end %>

app/views/locations/new.js.erb
<%= smart_listing_update(:locations) %>

app/views/smart_listing/_action_custom.html.erb
<%# 
  Custom action.

  Available local variables:
    url
    icon
    html_options:       custom html options
-%>

<%= link_to_if(action_if, content_tag(:span, '', :class => icon, :title => title), url, html_options) %>

app/views/smart_listing/_action_delete.html.erb
<%# 
  Delete action.

  Available local variables:
    action_if:          false if action is disabled
    url:                destroy url
    icon:               icon css classes
    confirmation:       confrimation text
    title
-%>

<%= link_to_if(action_if, content_tag(:i, "", :class => icon), url, :remote => true, :class => "destroy", :method => :delete, :title => title || t("smart_listing.actions.destroy"), :data => {:confirmation => confirmation || t("smart_listing.msgs.destroy_confirmation")} ) %>

app/views/smart_listing/_action_edit.html.erb
<%# 
  Edit action.

  Available local variables:
    action_if:          false if action is disabled
    url:                edit url
    icon:               icon css classes
    title
-%>

<%= link_to_if(action_if, content_tag(:i, '', :class => icon), url, :remote => true, :class => "edit", :title => title || t("smart_listing.actions.edit") ) %>

app/views/smart_listing/_action_show.html.erb
<%# 
  Show action.

  Available local variables:
    action_if:          false if action is disabled
    url:                show url
    icon:               icon clss classes
    title
-%>

<%= link_to_if(action_if, content_tag(:i, '', :class => icon), url, :class => "show", :title => title || t("smart_listing.actions.show") ) %>

app/views/smart_listing/_item_new.html.erb
<%# 
  New list item element (contains new item placeholder and add button).

  Available local variables:
    placeholder_classes:      classes for the main container
    new_item_action_classes:  new item action classes
    colspan              
    no_items_classes:         no items container classes
    no_items_text:            no items text displayed inside container
    new_item_button_url:      argument to link_to (new item button)
    new_item_button_classes
    new_item_button_text
    new_item_autoshow         automatically show new item placeholder
    new_item_content          new item placeholder content (usually some form)
-%>

<%= content_tag(:tr, '', :class => placeholder_classes + %w{info}, :data => {smart_listing_config.data_attributes(:autoshow) => new_item_autoshow}) do %>
  <%= new_item_content %>
<% end %>
<%= content_tag(:tr, :class => new_item_action_classes + %w{info}) do %>
  <%= content_tag(:td, :colspan => colspan) do %>
    <%= content_tag(:p, :class => no_items_classes + %w{pull-left}) do %>
      <%= no_items_text %>
    <% end %>
    <%= link_to(new_item_button_url, :remote => true, :class => new_item_button_classes + %w{btn pull-right}) do %>
      <%= content_tag(:i, '', :class => smart_listing_config.classes(:icon_new)) %>
      <%= new_item_button_text %>
    <% end %>
  <% end %>
<% end %>

app/views/smart_listing/_pagination_per_page_link.html.erb
<%# 
  Pagination single per-page link.

  Available local variables:
    page:           page number
    url:            page url (if page is not selected)
    smart_listing:  current SmartListing instance
    builder:        current builder instance
-%>

<% name = page == 0 ? t('views.pagination.unlimited') : page %>
<%= url ? link_to(name, url, :remote => smart_listing.remote?) : content_tag(:span, name) %>

app/views/smart_listing/_pagination_per_page_links.html.erb
<%# 
  Pagination per-page links.

  Available local variables:
    container_classes:  classes for the main container
    per_page_sizes:     array of available per-page sizes
    smart_listing:      current SmartListing instance
    builder:            current builder instance
-%>

<%= content_tag(:div, :class => container_classes ) do %>
  <% if smart_listing.options[:paginate] && (smart_listing.count > smart_listing.page_sizes.first) %>
    <%= t('views.pagination.per_page') %>
    <% per_page_sizes.each do |p| %><%= builder.pagination_per_page_link p %><% break if p >= smart_listing.count %><% end %>
    |
  <% end %>
  <%= t('views.pagination.total') %>
  <%= content_tag(:span, smart_listing.count, :class => "count") %>
<% end %>

app/views/smart_listing/_sortable.html.erb
<%# 
  Sortable attribute listing header.

  Available local variables:
    container_classes:  classes for the main container
    url:                sortable link url
    attribute:          current attribute name
    title:              current attribute title
    order:              defines column sort order
    smart_listing:      current SmartListing instance
    builder:            current builder instance
-%>

<%= link_to url, :class => container_classes, :data => {:attr => attribute}, :remote => true do %>
  <%= title %>
  <% if order %>
    <span class="<%= order == "asc" ? smart_listing_config.classes(:icon_sort_up) : smart_listing_config.classes(:icon_sort_down) %>"></span>
  <% else %>
    <span class="<%= smart_listing_config.classes(:icon_sort_none) %>"></span>
  <% end %>
<% end %>